name: Build

on:
  push:
    branches:
      - main
    paths:
      - "Cargo.toml"
      - "meme_generator_contrib/**"
  pull_request_target:
    paths:
      - "Cargo.toml"
      - "meme_generator_contrib/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            label: windows-x86_64

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.85.0
      - uses: swatinem/rust-cache@v2

      - name: Rustup add target
        run: rustup target add ${{ matrix.platform.target }}

      - name: Build target
        run: cargo build --release --target ${{ matrix.platform.target }}

      - uses: actions/upload-artifact@v4
        with:
          name: "meme-generator-contrib-${{ matrix.platform.label }}"
          path: |
            target/${{ matrix.platform.target }}/release/*.dll
